server:
  port: 8080
  shutdown: graceful
  servlet:
    encoding:
      enabled: true
      force: true
      charset: ${file.encoding}

spring:
  datasource:
    url: jdbc:h2:tcp://10.167.227.242/~/test; #url: jdbc:h2:tcp://localhost/~/test
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
     defer-datasource-initialization: true
     ddl-auto: create
    properties:
      generate-ddl: true
      hibernate:
        show_sql: true
        format_sql: true
        globally_quoted_identifiers: true

logging.level:
  org.hibernate.SQL: debug

servlet:
  multipart:
    enabled : true
    location: C:\IdeaTec\image
    maxFileSize: 200MB
    maxRequestSize: 100MB


