port-server:
  port: 8080
  shutdown: graceful
  servlet:
    encoding:
      enabled: true
      force: true
      charset: ${file.encoding}

spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/test
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
     ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        globally_quoted_identifiers: true

logging.level:
  org.hibernate.SQL: debug